### ISSUE TITLE
小米7.1.1 扫描不到

### ISSUE THREAD

**Issue by ev3rs0u1** [bingerz/flip-ble#1]
小米 MAX 2 扫描不到蓝牙设备，开GPS或者怎么改配置都扫不到

**Comment by bingerz** [comment]
当前有个默认的Service UUID过滤项，你删掉试试？不好意思最近调试一些功能，加进去的默认设置，不小心提交上去了。

**Comment by bingerz** [comment]
> 小米 MAX 2 扫描不到蓝牙设备，开GPS或者怎么改配置都扫不到

MainActivity的代码中，有一个默认的ServiceUuid过滤项（1803那个服务），删掉试试呢？
PS：抱歉哈，最近调试功能加入的默认服务限制，不小心提交上去了。

**Comment by ev3rs0u1** [comment]
感谢回复，不过我不是用demo测试的，是在app引入这个库后使用小米手机才发现的（或者是
7.1系统），其他品牌暂时没有发现这个问题，而且我只用了Name过滤

**Comment by bingerz** [comment]
> 感谢回复，不过我不是用demo测试的，是在app引入这个库后使用小米手机才发现的（或者是
> 7.1系统），其他品牌暂时没有发现这个问题，而且我只用了Name过滤

LeScannerForLollipop->getNewLeScanCallback()->onScanFailed(int errorCode)有回调什么错误信息么？
是从引用本库就扫描不到设备，替换回别的方法就可以扫描到设备么？
如果换其他库或者实现方法都扫描不到，可以尝试重启一下蓝牙或者手机，如果还不OK，可以可以给我一些蓝牙协议栈日志，我分析一下问题。

**Comment by ev3rs0u1** [comment]
> > 感谢回复，不过我不是用demo测试的，是在app引入这个库后使用小米手机才发现的（或者是
> > 7.1系统），其他品牌暂时没有发现这个问题，而且我只用了Name过滤
> 
> LeScannerForLollipop->getNewLeScanCallback()->onScanFailed(int errorCode)有回调什么错误信息么？
> 是从引用本库就扫描不到设备，替换回别的方法就可以扫描到设备么？
> 如果换其他库或者实现方法都扫描不到，可以尝试重启一下蓝牙或者手机，如果还不OK，可以可以给我一些蓝牙协议栈日志，我分析一下问题。

Github上主流的库都能扫到不过都要开启位置权限，甚至 onScanFailed 都看不到任何Log，不过我有时候又能扫出来（周期扫描等至少半分钟）
[蓝牙日志](https://share.weiyun.com/5cBSqSZ)

**Comment by bingerz** [comment]
> > > 感谢回复，不过我不是用demo测试的，是在app引入这个库后使用小米手机才发现的（或者是
> > > 7.1系统），其他品牌暂时没有发现这个问题，而且我只用了Name过滤
> > 
> > 
> > LeScannerForLollipop->getNewLeScanCallback()->onScanFailed(int errorCode)有回调什么错误信息么？
> > 是从引用本库就扫描不到设备，替换回别的方法就可以扫描到设备么？
> > 如果换其他库或者实现方法都扫描不到，可以尝试重启一下蓝牙或者手机，如果还不OK，可以可以给我一些蓝牙协议栈日志，我分析一下问题。
> 
> Github上主流的库都能扫到不过都要开启位置权限，甚至 onScanFailed 都看不到任何Log，不过我有时候又能扫出来（周期扫描等至少半分钟）
> [蓝牙日志](https://share.weiyun.com/5cBSqSZ)

抱歉哈，过了好几天才回复，我看到日志里面有连续的开启扫描-关闭扫描-开启扫描、关闭扫描-开启扫描-关闭扫描等等，每个操作间隔时间几百ms，当前您的扫描持续时间和扫描间隔策略是什么样子？我当前使用的间隔和持续时间都在几秒-几十秒的级别，还没用户反馈类似扫描的问题。如果能提供策略，我找设备复现一下。感觉跟扫描策略有些关系。

**Comment by ev3rs0u1** [comment]
扫描策略我怕自己乱配置到最后都是跟demo里写一样
