### ISSUE TITLE
作者你好，能都加一个监听Bond的方法

### ISSUE THREAD

**Issue by Alexxiaopang** [bingerz/flip-ble#2]
现在市面上很多Ble都需要Bond，能否提供一个方法，在connect前先Bond一下，谢谢

**Comment by bingerz** [comment]
> 现在市面上很多Ble都需要Bond，能否提供一个方法，在connect前先Bond一下，谢谢

可以和我详细说一下这个需求么？
PS：最近被客户追着，没有腾出精力来回复您的问题，非常抱歉。

**Comment by Alexxiaopang** [comment]
现在的ble很多都需要bond（虽说ble不bond也能连接，但是加密的信息还是需要bond），其实应该提供另一个场景： bonded判定--->bond--->连接；这个场景可选。

**Comment by GirlFriendNotFind** [comment]
维护了同一个？这是最新版本吗？https://github.com/Jasonchenlijian/FastBle

**Comment by bingerz** [comment]
> 

不是，只维护当前这个。
